# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

  - task: gitversion/execute@0
    displayName: Determine Version

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/AspNetCore.Identity.DocumentDb.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/AspNetCore.Identity.DocumentDb.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion 

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'befc8922-2410-426a-b4f8-82e7be18d14d/a1379d5e-c87b-45bd-9bd4-281ef2317f10'
